### ISSUE TITLE
why no weighted PROBIT estimator?

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#119]

**Comment by tomaszaba** [comment]
I think this is simply because SMART does not do that, and our goal was to mimic what SMART does. I think this is the reason why.

**Comment by ernestguevarra** [comment]
Does the PROBIT report confidence intervals? Does the SMART ENA report confidence intervals with their probit use?

One of the key things that SMART has used against PROBIT is that there is supposedly no agreed approach for estimating confidence intervals on a PROBIT.

**Comment by tomaszaba** [comment]
> Does the PROBIT report confidence intervals? Does the SMART ENA report confidence intervals with their probit use?
> 

No. Just the point estimate. 

> 
> 
> One of the key things that SMART has used against PROBIT is that there is supposedly no agreed approach for estimating confidence intervals on a PROBIT.

I see. They do not report the confidence intervals.
