### ISSUE TITLE
TESTING check `rhub_check()` results and address all errors, warnings, notes

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#25]
`rhub_check()` results as at 28 October 2024

* linux r-devl: https://github.com/nutriverse/mwana/actions/runs/11541645078/job/32123888209
* windows r-devel: https://github.com/nutriverse/mwana/actions/runs/11541645078/job/32123888351
* macos r-devel: https://github.com/nutriverse/mwana/actions/runs/11541645078/job/32123888456

**Comment by tomaszaba** [comment]
All working. Rebuilt with R version 4.4.2
