### ISSUE TITLE
find most suitable hex sticker

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#31]
@tomaszaba, what do you think of this?

![mwana](https://github.com/user-attachments/assets/558c58cd-94e5-4857-8605-a100fab430c6)

Photo by <a href="https://unsplash.com/@renebbernal?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">[Rene Bernal](https://unsplash.com/@renebbernal?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash)</a> on <a href="https://unsplash.com/photos/silhouette-of-childrens-running-on-hill-f0rdHx5P8sQ?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">[Unsplash](https://unsplash.com/photos/silhouette-of-childrens-running-on-hill-f0rdHx5P8sQ?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash)</a>

**Comment by tomaszaba** [comment]
Hi @ernestguevarra, 
This looks nice, but I want the hex sticker to have a touch of Africa as is the term `mwana`. I am still thinking about it.

**Comment by ernestguevarra** [comment]
![logo](https://github.com/user-attachments/assets/094c866c-1940-4678-880a-4a46a8d63a8c)

@tomaszaba here is a suggested hex sticker for the package. It took me time to find the right photo for the centre of the logo. I bought this photo so we own the rights to it now.

**Comment by ernestguevarra** [comment]
![logo](https://github.com/user-attachments/assets/c3f15b56-dc1f-43df-a656-57e96457624d)

**Comment by tomaszaba** [comment]
> ![logo](https://github.com/user-attachments/assets/c3f15b56-dc1f-43df-a656-57e96457624d)
> 
> 

Great. I think I like this way.
