### ISSUE TITLE
change package name to mwana

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#63]
@tomaszaba I think it might be good to change the name to `mwana` now rather than later. In each of your past two PRs, you have needed to change quite a lot of files already. I think changing ipccheckr to mwana should be straightforward and can be done with just a simple find and replace on Rstudio GUI. once all are changed, just to `devtools::document()` and that should update the package. I think if we are changing to many files already anyway, it is better that we fix that one first now so we are in a good mindset for what this package is. And I can do a lot of the other background stuff preparing the package for everything else.

See what you think.

**Comment by tomaszaba** [comment]
@ernestguevarra I agree. I will do that in my next branch. Thanks

**Comment by tomaszaba** [comment]
> @tomaszaba I think it might be good to change the name to `mwana` now rather than later. In each of your past two PRs, you have needed to change quite a lot of files already. I think changing ipccheckr to mwana should be straightforward and can be done with just a simple find and replace on Rstudio GUI. once all are changed, just to `devtools::document()` and that should update the package. I think if we are changing to many files already anyway, it is better that we fix that one first now so we are in a good mindset for what this package is. And I can do a lot of the other background stuff preparing the package for everything else.
> 
> See what you think.

Done.
