### ISSUE TITLE
SUGGESTION: change approach to syntax of examples in all functions

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#64]
Currently, almost all (if not all) functions start something like this:

```R
df |>
  name_of_function(second_argument, third_argument,...)
```

See this from the point of a general user and it is not very helpful to see the use of pipe from an object or a data.frame then to the function. Most people should be able to understand this but the principle of an example is to show how to normally use the function and the normal use of a function is not necessarily in a pipe context but in its usual, standard form:

```R
name_of_function(first_argument, second_argument, third_argument....)
```

Whilst use of a pipe is a good thing, all functions should be usable without pipes...

**Comment by tomaszaba** [comment]
Noted. Will do that.

**Comment by tomaszaba** [comment]
@ernestguevarra , 

In this example:
```r
#'   anthro.02 |>
#'   mw_wrangle_age(
#'     dos = NULL,
#'     dob = NULL,
#'     age = age,
#'     .decimals = 2
#'   ) |>
#'   mw_wrangle_muac(
#'     sex = sex,
#'     age = age,
#'     muac = muac,
#'     .recode_sex = TRUE,
#'     .recode_muac = TRUE,
#'     .to = "cm",
#'     .decimals = 3
#'   )
```

Do I have to do this: 

```r
#'   x <- mw_wrangle_age(
#'   df = anthro.02,
#'     dos = NULL,
#'     dob = NULL,
#'     age = age,
#'     .decimals = 2
#'   )
```

and then I do: 

```r
#'   mw_wrangle_muac(
#'    df = x, 
#'    sex = sex,
#'     age = age,
#'     muac = muac,
#'     .recode_sex = TRUE,
#'     .recode_muac = TRUE,
#'     .to = "cm",
#'     .decimals = 3
#'   )
```

**Comment by ernestguevarra** [comment]
yes, that is what most people will do. Remember, the example is for the second function `mw_wrangle_muac`, not for wrangle age.

**Comment by ernestguevarra** [comment]
> > yes, that is what most people will do. Remember, the example is for the second function `mw_wrangle_muac`, not for wrangle age.
> 
> Great. Let me find a way of getting rid of the first code and call the main function right away. Or I put a comment to say "prepare the data" and the other one applying the actual function.

you can add the wrangle age there, maybe just annotate that the next function only works if age has been processed already (which again should be documented in your wrangle muac function). I think I made a comment about this ages ago).

**Comment by tomaszaba** [comment]
> > > yes, that is what most people will do. Remember, the example is for the second function `mw_wrangle_muac`, not for wrangle age.
> > 
> > 
> > Great. Let me find a way of getting rid of the first code and call the main function right away. Or I put a comment to say "prepare the data" and the other one applying the actual function.
> 
> you can add the wrangle age there, maybe just annotate that the next function only works if age has been processed already (which again should be documented in your wrangle muac function). I think I made a comment about this ages ago).

Ok. Noted.
