### ISSUE TITLE
are the internal datasets found in R/sysdata.rda the same datasets that are found in `data`

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#71]
When loading the contents of `R/sysdata.rda`, I see:

```R
mfaz.01
mfaz.02
wfhz.01
```

There are also datasets in `data` that have the same names. Are these the same datasets? if so, then it would be more appropriate to have them as internal datasets or exported datasets, not both.

if you decide to keep them internal, then remove the ones inside the `data` folder and then remove the corresponding documentation for these datasets. Internal datasets do not need documentation.

if you decide to use the datasets in `data`, then remove `R/sysdata.rda`

**Comment by tomaszaba** [comment]
> When loading the contents of `R/sysdata.rda`, I see:
> 
> 
> 
> ```R
> 
> mfaz.01
> 
> mfaz.02
> 
> wfhz.01
> 
> ```
> 
> 
> 
> There are also datasets in `data` that have the same names. Are these the same datasets? if so, then it would be more appropriate to have them as internal datasets or exported datasets, not both.
> 
> 
> 
> if you decide to keep them internal, then remove the ones inside the `data` folder and then remove the corresponding documentation for these datasets. Internal datasets do not need documentation.
> 
> 
> 
> if you decide to use the datasets in `data`, then remove `R/sysdata.rda`

These files I want to keep them as internal. The exported ones are those I named as `anthro.0*`.

**Comment by ernestguevarra** [comment]
If you look at the contents of your `data` folder in your current branch by issuing this command:

```R
list.files("data")
```

you will see:

```R
> list.files("data")
[1] "anthro.01.rda" "anthro.02.rda" "anthro.03.rda" "anthro.04.rda" "mfaz.01.rda"   "mfaz.02.rda"  
[7] "wfhz.01.rda"  
```

**Comment by tomaszaba** [comment]
@ernestguevarra I need your help on this. 
I tried to fix this bug, but it creates an error in the development workflow. Is the problem related to the fact that I documented the files in `R/data.R`? 

You will not see this error in the PR that I just raised because I cancelled changes made on this. 

```r
 > ## With `.from` set to "zscores" ----
   > remove_flags(
   +   x = wfhz.01$wfhz,
   +   .from = "zscores"
   + )
   Error: object 'wfhz.01' not found
   Execution halted
```

**Comment by ernestguevarra** [comment]
see this [comment](https://github.com/nutriverse/mwana/pull/72#issuecomment-2453767809) that I made to your latest PR.

**Comment by tomaszaba** [comment]
> see this [comment](https://github.com/nutriverse/mwana/pull/72#issuecomment-2453767809) that I made to your latest PR.

Noted. I believe we can consider this issue completed.
