### ISSUE TITLE
Question: should we add references in vignettes?

### ISSUE THREAD

**Issue by tomaszaba** [nutriverse/mwana#73]
In some functions we make a reference to resources used. I was wondering if we need do the same in vignettes, particularly the ones about IPC checks and plausibility checks?

**Comment by ernestguevarra** [comment]
I think this is a good idea. I think we should. Usually, on CRAN submission, the reviewer always asks for references in the DESCRIPTION file (links only) and references in the function documentation. They don't really read the vignettes in detail but I think it would be good to have references in vignettes

**Comment by tomaszaba** [comment]
Great. I will work on this when I am done with the prevalence functions.

**Comment by tomaszaba** [comment]
Done.
