### ISSUE TITLE
IDEA/SUGGESTION: possible title for package

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#74]
I think we've been discussing about what would be a good title for the package. Right now, we have it as **Utilities for analysing children’s nutritional status**.

I think this is OK. My main concern about this title (and I think you mentioned this as well) is that a general person (or even someone who does SMART or nutrition surveys in general) might not make the connection to what this package is about?

I think the following elements should be discernable from the title:

1. something that says that this is something that allows someone to work with or analyse data
2. That that data is child anthropometric data (more specific than just nutrition status which can be other things as well other than anthro)
3. and that this is for survey data

What do you think?

**Comment by tomaszaba** [comment]
I agree. On point one, I think to highlight that it's a nice package for working with multi-area datasets would be good. I think this is something I tried to say when I started revising the documentation (in the DESCRIPTION) but I was lacking the right word to described it.

**Comment by tomaszaba** [comment]
What about this: 

*A simple, streamlined workflow for plausibility checks and wasting prevalence estimation in R*

Or 

*An efficient workflow for plausibility checks and wasting prevalence estimation in R*

I think either of these covers the fundamental problem we aim to tackle with the package. I strived to keep it as short as possible; that comes with a cost: not many details can be added to a short title. Issues like survey data, multi-area, anthropometric data... I think they are dispensable and the title is self-explanatory. 

How do you find this suggestion?

**Comment by tomaszaba** [comment]
I have incorporated my suggestion above to see how it looks. I also revised the package description accordingly. Please review both.

**Comment by tomaszaba** [comment]
Thanks for sharing your thoughts on this. How about this: Utilities for plausibility check and prevalence analysis of wasting in R?

Or: Plausibility check and wasting prevalence analysis in R?

Please, you may suggest a new title or parts to improve.

**Comment by ernestguevarra** [comment]
Let us just remove the R in the title and then change wasting based on what we agree on (maybe acute undernutrition?)
